language: java
jdk:
  - oraclejdk8

# Make sure we have a new enough JDK, see https://github.com/travis-ci/travis-ci/issues/3259
sudo: required
dist: trusty

# Enable X Virtual Framebuffer in order to run UI tests
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

after_success:
  - mvn clean cobertura:cobertura coveralls:report
